default:
  ak4:
    pt: 30        # Min pt
    abseta: 5.0   # Max |eta|
    chf: 0.1      # Min chf     
    nhf: 0.8      # Max nhf     
  ht:
    abseta: 2.5   # Maximum jet eta for HT
    jetpt: 30     # Minimum pt on jets for HT
  muon:
    cuts:
      tight:
        pt : 20
        eta : 2.4
        iso : 0.15
      loose:
        pt : 10
        eta : 2.4
        iso : 0.25
  electron:
    cuts:
      tight:
        pt : 40
        eta : 2.5
      loose:
        pt : 10
        eta : 2.5
        dxy: # https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2
          barrel: 0.05
          endcap: 0.10
        dz: # https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2
          barrel: 0.10
          endcap: 0.20
    branch:
      id: Electron_cutBased
  photon:
    cuts:
      loose:
        pt: 15
        eta: 2.5
      tight:
        pt: 230
        pttrig: 230
    branch: # No eta cut here bc we use "isScEtaEB"
      id: Photon_cutBasedBitmap
      idv7: Photon_cutBased
  tau:
    cuts:
      pt: 20
      eta: 2.3
    branch:
      id: Tau_idDecayModeNewDMs
      iso: Tau_idDeepTau2017v2p1VSjet
  recoil:
    pt: 250       # Min recoil pt
  dpfcalo: 0.5    # Minimum Delta(PFMET,CaloMET)  
  studies:
    water_leak: False
    l1_turnon: False
    high_pu_fill: False
  run:
    regions: '.*'
    kinematics:
      save: False
      events:
        - 492220275
    save_passing:
      regions: []       # Specify for which regions to save (run,lumi,event) info for passing events
    ranges: # Run ranges to analyze
      2023D_pixelInefficiency: [369864, 369873] # Fill 9007
      2023D_noPixelInefficiency: [369874, 370129]
  
  # Configuration of JECs to be applied to offline jets
  jecs: 
    offline:
      apply: true
      tag: Winter23Prompt23_RunA_V1_DATA

  # Lumi mask JSON files per year
  lumi_masks:
    2018: data/json/Cert_314472-325175_13TeV_17SeptEarlyReReco2018ABC_PromptEraD_Collisions18_JSON.txt
    2022: data/json/Cert_Collisions2022_355100_362760_Golden.json

  # MET filters on data and MC
  filters:
    data:
      - Flag_goodVertices
      - Flag_globalSuperTightHalo2016Filter
      - Flag_HBHENoiseFilter
      - Flag_HBHENoiseIsoFilter
      - Flag_EcalDeadCellTriggerPrimitiveFilter
      - Flag_BadPFMuonFilter
      - Flag_eeBadScFilter
      - Flag_ecalBadCalibFilterV2
    mc:
      - Flag_goodVertices
      - Flag_globalSuperTightHalo2016Filter
      - Flag_HBHENoiseFilter
      - Flag_HBHENoiseIsoFilter
      - Flag_EcalDeadCellTriggerPrimitiveFilter
      - Flag_BadPFMuonFilter
      - Flag_ecalBadCalibFilterV2